version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/django-app
    ports:
      - 8000:8000   
    image: application:django
    container_name: django_container
    command: gunicorn my_django.wsgi:application --bind 0.0.0.0:8000
    